[package]
name = "typed-type-exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
educe = "0.4"
enum-as-inner = "0.4"
match_template = { git = "https://github.com/tikv/tikv.git" }
